import { createFileRoute, Outlet } from '@tanstack/react-router'
import { AuthLayout } from '../components/auth/AuthLayout'
import { AuthCard } from '../components/auth/AuthCard'

// @ts-expect-error - Route tree is generated by ShipKit assembler
export const Route = createFileRoute('/_auth')({
  component: AuthLayoutComponent,
})

function AuthLayoutComponent() {
  return (
    <AuthLayout>
      <AuthCard>
        <Outlet />
      </AuthCard>
    </AuthLayout>
  )
}
