import { createFileRoute, Link } from '@tanstack/react-router'
import { SignupForm } from '../components/auth/SignupForm'
import { AuthHeader } from '../components/auth/AuthHeader'
import { AuthFooter } from '../components/auth/AuthFooter'

// @ts-expect-error - Route tree is generated by ShipKit assembler
export const Route = createFileRoute('/_auth/signup')({
  component: SignupPage,
})

function SignupPage() {
  return (
    <>
      <AuthHeader 
        title="Create an account" 
        description="Enter your information to get started" 
      />
      <div className="p-6 pt-0">
        <SignupForm />
      </div>
      <AuthFooter>
        Already have an account?{' '}
        <Link to="/login" className="underline underline-offset-4 hover:text-primary">
          Sign in
        </Link>
      </AuthFooter>
    </>
  )
}

