import { createFileRoute } from '@tanstack/react-router'
import { AuthHeader } from '../components/auth/AuthHeader'
import { Loader2 } from 'lucide-react'
import * as React from 'react'

// @ts-expect-error - Route tree is generated by ShipKit assembler
export const Route = createFileRoute('/_auth/auth/callback')({
  component: AuthCallbackPage,
})

function AuthCallbackPage() {
  React.useEffect(() => {
    // Placeholder: Auth Engine callback processing injected by ShipKit
    console.log("Processing auth callback...")
  }, [])

  return (
    <>
      <AuthHeader 
        title="Authenticating" 
        description="Please wait while we complete your authentication." 
      />
      <div className="p-6 pt-0 flex justify-center items-center py-10">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    </>
  )
}

