import { createFileRoute, Link } from '@tanstack/react-router'
import { LoginForm } from '../components/auth/LoginForm'
import { AuthHeader } from '../components/auth/AuthHeader'
import { AuthFooter } from '../components/auth/AuthFooter'

// @ts-expect-error - Route tree is generated by ShipKit assembler
export const Route = createFileRoute('/_auth/login')({
  component: LoginPage,
})

function LoginPage() {
  return (
    <>
      <AuthHeader 
        title="Welcome back" 
        description="Enter your email to sign in to your account" 
      />
      <div className="p-6 pt-0">
        <LoginForm />
      </div>
      <AuthFooter>
        Don't have an account?{' '}
        <Link to="/signup" className="underline underline-offset-4 hover:text-primary">
          Sign up
        </Link>
      </AuthFooter>
    </>
  )
}
