import { createFileRoute, Link } from '@tanstack/react-router'
import { ForgotPasswordForm } from '../components/auth/ForgotPasswordForm'
import { AuthHeader } from '../components/auth/AuthHeader'
import { AuthFooter } from '../components/auth/AuthFooter'

// @ts-expect-error - Route tree is generated by ShipKit assembler
export const Route = createFileRoute('/_auth/forgot-password')({
  component: ForgotPasswordPage,
})

function ForgotPasswordPage() {
  return (
    <>
      <AuthHeader 
        title="Forgot Password" 
        description="Enter your email to receive a password reset link." 
      />
      <div className="p-6 pt-0">
        <ForgotPasswordForm />
      </div>
      <AuthFooter>
        Remember your password?{' '}
        <Link to="/login" className="underline underline-offset-4 hover:text-primary">
          Sign in
        </Link>
      </AuthFooter>
    </>
  )
}

