import { createFileRoute, Link } from '@tanstack/react-router'
import { AuthHeader } from '../components/auth/AuthHeader'
import { AuthFooter } from '../components/auth/AuthFooter'
import { AlertCircle } from 'lucide-react'

// Allow search params for error messages
// @ts-expect-error - Route tree is generated by ShipKit assembler
export const Route = createFileRoute('/_auth/auth/error')({
  validateSearch: (search: Record<string, unknown>) => {
    return {
      message: (search.message as string) || 'An unknown authentication error occurred.',
    }
  },
  component: AuthErrorPage,
})

function AuthErrorPage() {
  const { message } = Route.useSearch()

  return (
    <>
      <AuthHeader 
        title="Authentication Error" 
        description="There was a problem signing you in." 
      />
      <div className="p-6 pt-0 flex flex-col items-center justify-center gap-4 text-center">
        <div className="h-12 w-12 rounded-full bg-destructive/15 flex items-center justify-center text-destructive">
          <AlertCircle className="h-6 w-6" />
        </div>
        <p className="text-sm text-muted-foreground">
          {message}
        </p>
      </div>
      <AuthFooter>
        <Link to="/login" className="underline underline-offset-4 hover:text-primary">
          Try again
        </Link>
      </AuthFooter>
    </>
  )
}

