import { createFileRoute, Link } from '@tanstack/react-router'
import { VerifyEmailForm } from '../components/auth/VerifyEmailForm'
import { AuthHeader } from '../components/auth/AuthHeader'
import { AuthFooter } from '../components/auth/AuthFooter'

// @ts-expect-error - Route tree is generated by ShipKit assembler
export const Route = createFileRoute('/_auth/verify-email')({
  component: VerifyEmailPage,
})

function VerifyEmailPage() {
  return (
    <>
      <AuthHeader 
        title="Verify your email" 
        description="Enter the verification code sent to your email address." 
      />
      <div className="p-6 pt-0">
        <VerifyEmailForm />
      </div>
      <AuthFooter>
        <Link to="/login" className="underline underline-offset-4 hover:text-primary">
          Back to login
        </Link>
      </AuthFooter>
    </>
  )
}

