import { createFileRoute, Link } from '@tanstack/react-router'
import { ResetPasswordForm } from '../components/auth/ResetPasswordForm'
import { AuthHeader } from '../components/auth/AuthHeader'
import { AuthFooter } from '../components/auth/AuthFooter'

// @ts-expect-error - Route tree is generated by ShipKit assembler
export const Route = createFileRoute('/_auth/reset-password')({
  component: ResetPasswordPage,
})

function ResetPasswordPage() {
  return (
    <>
      <AuthHeader 
        title="Reset Password" 
        description="Enter your new password below." 
      />
      <div className="p-6 pt-0">
        <ResetPasswordForm />
      </div>
      <AuthFooter>
        Remember your password?{' '}
        <Link to="/login" className="underline underline-offset-4 hover:text-primary">
          Sign in
        </Link>
      </AuthFooter>
    </>
  )
}

